### ISSUE TITLE
Port outside the component

### ISSUE THREAD

**Issue by brollb** [symbench/scm#121]
It appears that ports can be outside the parent by a pixel. I suspect this is due to rounding errors:
![DeepinScreenshot_select-area_20210701110303](https://user-images.githubusercontent.com/4982789/124155292-f3accf80-da5b-11eb-9927-399d6249ed6e.png)

**Comment by umesh-timalsina** [comment]
Another instance of the issue:
![image](https://user-images.githubusercontent.com/11476842/125995272-eee9afc1-0966-44fd-9677-f8c5f5e3911d.png)

**Comment by umesh-timalsina** [comment]
Is this fixed @brollb? I no longer encounter this.

**Comment by brollb** [comment]
I haven't seen this in a while either so I suspect it might be. (I don't recall for sure.) We can probably go ahead and close it and revisit it if it occurs again.
