### ISSUE TITLE
Group downloaded annotations by source url.

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#125]
It might be nice to group downloaded annotations by source URL. May be have a different button for downloading those annotations? Thoughts @brollb ?

**Comment by brollb** [comment]
Hmm... I had been imagining that the structure of the zip file would simply contain a list of the annotations (say "image1.json", "image2.json", etc). Are they currently downloaded as a single annotations file?

**Comment by umesh-timalsina** [comment]
Yeah. The current structure of the `zip` file is:
1. All the images
2. Single annotation.json

**Comment by brollb** [comment]
Gotcha. Yeah, I think splitting them up is a good idea. We can probably omit the image files since they are available via url
