### ISSUE TITLE
Meaningful port labels

### ISSUE THREAD

**Issue by brollb** [symbench/scm#16]
Currently, there is a single category, "port". It would be great if we could select meaningful port labels such as "emitter", "base", and "collector" for an NPN transistor.

**Comment by umesh-timalsina** [comment]
Related to #21, I will add the port information to the json itself. Once we have that in place, I guess we can move forward with this suggestion. Related to #18 as well.

**Comment by brollb** [comment]
This is now possible as of 43d98ed5d6a4e1f18aefd546ed464e8954cc0dae
