### ISSUE TITLE
Variable length port annotations?

### ISSUE THREAD

**Issue by brollb** [symbench/scm#175]
There isn't a good way to add ports to subcircuits currently. This will need to be addressed somehow...
![DeepinScreenshot_select-area_20210712120313](https://user-images.githubusercontent.com/4982789/125327681-fc798d00-e308-11eb-9b1d-088035da04c0.png)

**Comment by umesh-timalsina** [comment]
This might be handled by the workflow described in #131.

**Comment by brollb** [comment]
Yeah, this has been addressed by #131 as @umesh-timalsina said
