### ISSUE TITLE
OCR Helper Widget for PortAnnotation Mode

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#239]
For named ports in subcircuits, it is annoying to having type the name of the port for every annotation we create. It might be nice to incorporate a simple OCR helper when in port annotation mode that tries to recognize the characters of a named port. While the functionality seems primitive, we need to jump quite a few hoops to accomplish this, listed below:

1. Swap the comment widget (default) with another widget 
2. Upon `createSelection` in port annotation mode, select the image snippet and use a plugin to set widget text (based on OCR results).

**Comment by brollb** [comment]
Here is a screenshot of what @umesh-timalsina is describing:
![DeepinScreenshot_select-area_20210922125749](https://user-images.githubusercontent.com/4982789/134396575-75494c29-cdaa-4e03-80af-000f9a6d62f4.png)

I think this might only be needed for Circuit ports (ie, `Port` types). When we label text, this could be useful there, too. Can you think of any other cases, @umesh-timalsina?

**Comment by umesh-timalsina** [comment]
Yeah, I have added the feature keeping that in mind. For now, starting out simple with `pytessaract` (i.e. tesseract)'s default settings, which work well for selected snippets.
