### ISSUE TITLE
REST API for annotation pipeline

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#26]
This probably is the best issue to track this, so I am adding it here:

What's lacking in the current architecture (Non-Exhaustive List):
1. Uses Component and Port Names and Annotation Colors from a JSON file rather than requesting server.
2. With #25, port detection workflow has been added but it uses example json file rather than server capabilities. See the workflow checklist in #25, [here](https://github.com/symbench/scm/pull/25#issue-657946863).

For enhancements, we need a a well defined REST API with the following capabilities:
1. Endpoints that get rid of the `json` files from the front end.
2. Annotation Pipeline endpoints with port detection capbilities.

This is just a suggestion, but I think it will get most of the issues resolved.

_Originally posted by @umesh-timalsina in https://github.com/symbench/scm/issues/2#issuecomment-851175991_

**Comment by brollb** [comment]
I think we can probably keep the JSON files on the front end for now. I am not sure if there is any advantage to hosting it on the server.

Port detection capabilities have been added but we still need to add support for an endpoint that determines the connectivity of an annotated diagram (adding junctions as needed).
