### ISSUE TITLE
Code Quality Tools and CI Setup

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#27]
We need the following:

1. `eslint` for Javascript section of the package
2. `black` and `isort` for Python
3. `pre-commit` configuration for 1 and 2

Options for CI:
- `super-linter` action for PR/Lint checks https://github.com/github/super-linter
- `pre-commit` CI for PR/Lint checks https://pre-commit.ci/

I am leaning towards the pre-commit CI.

**Comment by brollb** [comment]
I also lean toward pre-commit
