### ISSUE TITLE
Only display Prompt when mode switching is not possible

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#311]
It might be nice to only display the prompt whenever the switching to leaf mode isn't possible assuming. The other way to handle it should be something like a checkbox for the current session, prompting only once. Something like don't ask again?

**Comment by brollb** [comment]
I think this makes sense. We could show the current state in the top center of the screen or something to make it obvious what is being edited.

**Comment by umesh-timalsina** [comment]
Currently, the prompt is also showing undefined.
![image](https://user-images.githubusercontent.com/11476842/139881941-c8b31f6b-0ca3-49b9-ad6e-2ca2ae9bcd5d.png)
