### ISSUE TITLE
Embed annotation tool in webgme

### ISSUE THREAD

**Issue by brollb** [symbench/scm#449]
It would be worth exploring how we could achieve #431 by embedding the annotation tool in webgme. We will need to 
- refactor the UI to disable components that aren't needed when embedded in another (ie, the title bar)
- make a design studio that saves the annotations themselves in the model (editable with the annotation tool).

**Comment by umesh-timalsina** [comment]
Okay, here are some possibilities for the tool embedding as a visualizer:

1. It should be able to load in new Images based on a URL provided to it such that we don't have to create a new visualizer every time.
