### ISSUE TITLE
Disable tag validation for now?

### ISSUE THREAD

**Issue by brollb** [symbench/scm#51]
It might be nice to disable tag validation as we don't yet know how we will handle complex things like subcircuits or varying levels of abstraction. If validation is disabled, we can experiment more easily with how this should be handled. (It should probably be re-enabled later once we figure out how exactly we would like to handle subcircuits and abstract components.)

**Comment by umesh-timalsina** [comment]
Okay. We can probably only limit the checks to the following:
1. It should have a single element body with length 1.

**Comment by umesh-timalsina** [comment]
This would also mean we need to add some styles for `AgentCreated` section for components with no predefiend tags.
