### ISSUE TITLE
Ports missing on matched templates

### ISSUE THREAD

**Issue by brollb** [symbench/scm#64]
I see some ports missing on the matched templates. I suspect this is because the template matching occurs after I label the component but before I have labeled the detected ports. See V3 below (detected from V2).
![DeepinScreenshot_select-area_20210610100211](https://user-images.githubusercontent.com/4982789/121548807-f2473480-c9d2-11eb-949f-e87a9dbbb043.png)

**Comment by umesh-timalsina** [comment]
Is this still in issue?

**Comment by brollb** [comment]
I think this has been fixed
