### ISSUE TITLE
Annotating Ports

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#7]
It might be nice to extend the current annotations API for labeling ports as well. This should preferably happen in the server itself just to maintain consistency with the current calculations.

**Comment by umesh-timalsina** [comment]
While the basic support for annotating ports exist, we need the orientation of the original template vs. the matched template for port naming. This will be super helpful for automatic port detection. So, it might be nice to add another widget to support orientation.

**Comment by brollb** [comment]
The last comment isn't clear to me actually. What additional orientation information do you need from the user and why?

**Comment by umesh-timalsina** [comment]
I don't think it will be sufficient. Let me clarify with an example, here's an example NPN Transistor, Inorder to detect ports of the Transistor (C, B, E) and possibly all other Transistors in the circuit image, we need the following information IMO.

![image](https://user-images.githubusercontent.com/11476842/119377801-260c2580-bc83-11eb-9475-b1a3b94cfeaf.png)

1. The original port locations. In order to do this in an automated fashion, we need to know if the transistor is horizontal or vertical. This will not matter for passive components like `Resistor` or `Capacitor` but will eventually matter for Transistors, MoSFETS. 

2. For other matched templates, the pipeline works even if the component is rotated but we need to have the base information of the original template and their port locations such that we can infer the effects of rotation on port location. 


Am I missing something?

**Comment by brollb** [comment]
Hmm... It still isn't obvious why the user would need to provide orientation information. When you mention "automatic port detection" are you imagining for the first annotation? Or recognizing other components from the original (user-provided) annotation?

This is how I have been imagining the workflow wrt port detection:
- User selects the component bounding box.
- User selects the (named) ports from the bounding box. Perhaps we detect the ports and the user simply provides labels from the expected labels given the component type.
- Component detection, etc, is performed.

When components are being detected, we know which version of the template was matched (ie, same orientation, +90, +180, +270) and should be able to update the ports accordingly. Then these port positions can be used during the connection step and we should be all set.

How does this compare to what you are thinking?

**Comment by umesh-timalsina** [comment]
I was thinking the following pipeline:
1. User selects a component and the direction of the Component. Based on this information, we detect the port location names for the original annotation by the user.
2. For other machine detected components, we are in the same page.

**Comment by brollb** [comment]
How do we detect the port location names for the first annotation? Are you expecting to have some sort of existing examples or rules like "NPN has a base on the left, collector on top, and emitter on bottom in the standard orientation"? (Is this why you want the user to specify the direction of the component?)

**Comment by umesh-timalsina** [comment]
Yeah. Precisely. This will be relatively st. forward for most components except sub-circuits.
