### ISSUE TITLE
Annotate groups of diagrams at once

### ISSUE THREAD

**Issue by brollb** [symbench/scm#9]
It will be pretty important that we can reuse our annotations across all figures w/ the same style (at the very least). A couple possible inspirations:
- https://www.microsoft.com/en-us/research/video/machine-teaching-demo/
- https://iangilman.com/openseadragon/flickr/

A couple important considerations:
- How easy is it to catch errors in the annotations?
- How easily can you tell when images are completed? Should these be hidden? What if subsequent annotations change them?

**Comment by umesh-timalsina** [comment]
Okay. I am currently working on a navigator support. I will add a PR shortly with the changes for creating the navigator and bulk annotation support. I propose the following changes:
1. Serve the static image files from the server, with an API endpoint for the URL sources for the images. If there are too many images, may be a paged response can help. 
2. I am currently split between https://openseadragon.github.io/examples/ui-reference-strip/ and https://iangilman.com/openseadragon/flickr/ for the annotation navigator. The first is simple and works on click for an individual image but cannot summarize multiple images at once. The second is a bit slick, summarizes all the images but I think will have a significant cognitive load once the annotations will be loaded. I will probably start with the first one and see where things lead from there. 
3. Finally, I am thinking of removing the gh-pages branch and serving the svelte build files from the server itself. Though this can be done separately.

**Comment by umesh-timalsina** [comment]
This will be closed by #116
